import { Dimensions, StyleSheet } from 'react-native';

const { width: __DEVICE_WIDTH } = Dimensions.get('window');
// @ts-ignore
const __w = typeof globalThis !== 'undefined' && globalThis.__w ? globalThis.__w : __DEVICE_WIDTH;
// @ts-ignore
const __fs = typeof globalThis !== 'undefined' && globalThis.__fs ? globalThis.__fs : 1;

export const MAX_CARD_WIDTH = Math.min(1200, __w * 0.995);

export const itemCategories = {
  frutas: { name: 'Frutas', emoji: '🍎' },
  vegetais: { name: 'Vegetais', emoji: '🥕' },
  carnes: { name: 'Carnes', emoji: '🥩' },
  laticinios: { name: 'Laticínios', emoji: '🥛' },
  paes: { name: 'Pães', emoji: '🍞' },
  bebidas: { name: 'Bebidas', emoji: '🥤' },
  limpeza: { name: 'Limpeza', emoji: '🧽' },
  higiene: { name: 'Higiene', emoji: '🧴' },
  outros: { name: 'Outros', emoji: '📦' },
};

export const makeDetailStyles = (palette) =>
  StyleSheet.create({
    root: { flex: 1, backgroundColor: palette.bg },
    tabHolder: { position: 'absolute', top: 0, left: 0, right: 0, zIndex: 60 },
    backButton: {
      position: 'absolute',
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.card,
      borderWidth: 1,
      borderColor: palette.border,
      shadowColor: '#0B0B0B',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.12,
      shadowRadius: 6,
      elevation: 2,
    },
    container: { flex: 1, backgroundColor: palette.bg },
    scrollContent: { alignItems: 'center', paddingBottom: 32, paddingHorizontal: 8 },
    card: {
      backgroundColor: palette.card,
      borderRadius: 20,
      padding: 16,
      marginBottom: 18,
      width: '100%',
      maxWidth: MAX_CARD_WIDTH,
      shadowColor: '#0B0B0B',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 6,
    },
    cardTitle: {
      fontSize: 20 * __fs,
      fontWeight: 'bold',
      color: palette.text,
      marginBottom: 10,
    },
    headerInput: {
      backgroundColor: palette.card,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      color: palette.text,
      borderWidth: 1,
      borderColor: palette.border,
    },
    headerNameInput: { fontSize: 18 * __fs, fontWeight: '700' },
    headerDescInput: { marginTop: 8, minHeight: 72 },
    inputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
      gap: 10,
    },
    input: {
      backgroundColor: palette.card,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: palette.border,
      fontSize: 15 * __fs,
      color: palette.text,
    },
    addButton: {
      backgroundColor: palette.primary,
      borderRadius: 12,
      paddingVertical: 12,
      alignItems: 'center',
      alignSelf: 'flex-start',
      minHeight: 44,
      paddingHorizontal: 14,
    },
    addButtonText: {
      color: '#fff',
      fontWeight: 'bold',
    },
    sectionTitle: {
      width: '100%',
      maxWidth: MAX_CARD_WIDTH,
      fontSize: 18 * __fs,
      fontWeight: 'bold',
      color: palette.text,
      marginBottom: 10,
    },
    progressBarWrap: {
      marginTop: 12,
    },
    progressBarBg: {
      width: '100%',
      height: 10,
      backgroundColor: palette.border,
      borderRadius: 999,
      overflow: 'hidden',
    },
    progressBarFill: {
      height: '100%',
      backgroundColor: palette.primary,
    },
    progressText: {
      color: palette.mutedText,
      marginTop: 6,
    },
    actionsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 12,
    },
    actionChip: {
      borderWidth: 1,
      borderColor: palette.border,
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 12,
      backgroundColor: palette.card,
      minHeight: 44,
      alignSelf: 'flex-start',
    },
    actionChipText: {
      color: palette.text,
      fontWeight: '600',
    },
    itemCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: palette.card,
      borderRadius: 16,
      padding: 14,
      width: '100%',
      maxWidth: MAX_CARD_WIDTH,
      marginBottom: 10,
      shadowColor: '#0B0B0B',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 6,
      elevation: 2,
    },
    swipeActionLeft: {
      width: 88,
      marginVertical: 5,
      marginLeft: 8,
      borderRadius: 16,
      backgroundColor: palette.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    swipeActionRight: {
      width: 88,
      marginVertical: 5,
      marginRight: 8,
      borderRadius: 16,
      backgroundColor: palette.danger,
      alignItems: 'center',
      justifyContent: 'center',
    },
    swipeActionText: { color: '#fff', fontWeight: '700', fontSize: 13 },
    checkWrap: {
      marginRight: 10,
    },
    checkCircle: {
      width: 28,
      height: 28,
      borderRadius: 14,
      borderWidth: 2,
      borderColor: palette.border,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.card,
    },
    checkCircleOn: {
      backgroundColor: palette.success,
      borderColor: palette.success,
    },
    itemCardPurchased: {
      opacity: 0.6,
    },
    itemName: {
      fontSize: 16 * __fs,
      fontWeight: 'bold',
      color: palette.text,
    },
    itemNamePurchased: {
      textDecorationLine: 'line-through',
      color: palette.mutedText,
    },
    itemSubText: {
      color: palette.mutedText,
      marginTop: 2,
      fontSize: 14 * __fs,
    },
    metaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 6,
    },
    qtyBox: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: palette.altSurface,
      borderRadius: 10,
      overflow: 'hidden',
    },
    qtyBtn: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      minWidth: 36,
      minHeight: 36,
      alignItems: 'center',
      justifyContent: 'center',
    },
    qtyBtnText: {
      fontSize: 18 * __fs,
      color: palette.text,
    },
    qtyValue: {
      minWidth: 26,
      textAlign: 'center',
      fontWeight: '700',
      color: palette.text,
    },
    pricePill: {
      backgroundColor: palette.altSurface,
      borderRadius: 999,
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: palette.border,
    },
    itemTotal: {
      marginLeft: 8,
      backgroundColor: palette.altSurface,
      borderColor: palette.success,
      borderWidth: 1,
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderRadius: 999,
    },
    itemTotalText: { color: palette.success, fontWeight: '700' },
    savingBadge: { paddingVertical: 4, paddingHorizontal: 8, borderRadius: 8, marginLeft: 4 },
    savingPos: {
      backgroundColor: palette.altSurface,
      borderWidth: 1,
      borderColor: palette.success,
    },
    savingNeg: { backgroundColor: palette.altSurface, borderWidth: 1, borderColor: palette.danger },
    savingBadgeText: { fontSize: 11 * __fs, fontWeight: '700', color: palette.text },
    priceText: {
      color: palette.primary,
      fontWeight: '700',
    },
    priceEditRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    pricePrefix: { color: palette.mutedText, marginRight: 4 },
    priceInput: {
      minWidth: 72,
      paddingVertical: 0,
      paddingHorizontal: 0,
      color: palette.text,
      fontSize: 15 * __fs,
    },
    priceSave: { color: palette.success, fontWeight: '700', marginLeft: 6 },
    membersRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
    },
    memberAvatarBox: {
      alignItems: 'center',
      width: 96,
    },
    memberAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 6,
    },
    memberAvatarText: {
      color: '#fff',
      fontWeight: 'bold',
    },
    memberName: {
      fontSize: 12 * __fs,
      color: palette.text,
      marginBottom: 6,
    },
    memberButton: {
      borderRadius: 10,
      paddingVertical: 6,
      paddingHorizontal: 10,
    },
    memberButtonAdd: {
      backgroundColor: 'transparent',
    },
    memberButtonRemove: {
      backgroundColor: 'transparent',
    },
    memberButtonText: {
      fontSize: 12 * __fs,
      color: palette.text,
    },
    archiveButton: {
      backgroundColor: '#111827',
      borderRadius: 14,
      paddingVertical: 12,
      paddingHorizontal: 16,
      alignItems: 'center',
      alignSelf: 'flex-start',
      minHeight: 46,
      marginBottom: 24,
    },
    archiveButtonText: {
      color: '#fff',
      fontWeight: 'bold',
      fontSize: 15 * __fs,
    },
    centered: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.bg,
    },
    emptyText: {
      color: palette.mutedText,
      fontSize: 14 * __fs,
    },
    statsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
    },
    statBox: {
      backgroundColor: palette.altSurface,
      borderRadius: 12,
      paddingVertical: 10,
      paddingHorizontal: 12,
      minWidth: 90,
    },
    statLabel: { color: palette.mutedText },
    statValue: { color: palette.text, fontWeight: '700', marginTop: 2 },
    snackbar: {
      position: 'absolute',
      left: 16,
      right: 16,
      bottom: 24,
      backgroundColor: palette.snackbarBg,
      paddingVertical: 12,
      paddingHorizontal: 18,
      borderRadius: 14,
      flexDirection: 'row',
      alignItems: 'center',
      shadowColor: '#0B0B0B',
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 6,
    },
    snackbarText: { color: '#fff', fontSize: 14 * __fs, fontWeight: '500' },
    snackbarUndo: { color: palette.primary, fontSize: 14 * __fs, fontWeight: '700' },
  });
