import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    mainContainer: { flex: 1, backgroundColor: '#f3f4f6' },
    container: { flex: 1, padding: 20 },
    containerCenter: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 20, backgroundColor: '#f3f4f6' },
    title: { fontSize: 32, fontWeight: 'bold', color: '#111827', marginBottom: 20 },
    header: { fontSize: 28, fontWeight: 'bold', color: '#111827', marginBottom: 10, flexShrink: 1 },
    input: { width: '100%', backgroundColor: 'white', padding: 15, borderRadius: 10, marginBottom: 10, borderWidth: 1, borderColor: '#d1d5db', fontSize: 16 },
    button: { width: '100%', backgroundColor: '#4f46e5', padding: 15, borderRadius: 10, alignItems: 'center', marginTop: 10 },
    buttonText: { color: 'white', fontWeight: 'bold', fontSize: 16 },
    buttonOutline: { width: '100%', backgroundColor: 'transparent', padding: 15, borderRadius: 10, alignItems: 'center', marginTop: 10, borderWidth: 2, borderColor: '#4f46e5' },
    buttonOutlineText: { color: '#4f46e5', fontWeight: 'bold', fontSize: 16 },
    buttonDanger: { width: '100%', backgroundColor: '#ef4444', padding: 15, borderRadius: 10, alignItems: 'center', marginTop: 20 },
    buttonSuccess: { width: '100%', backgroundColor: '#22c55e', padding: 15, borderRadius: 10, alignItems: 'center', marginTop: 20 },
    toggleText: { marginTop: 20, color: '#4f46e5', fontWeight: '500' },
    errorText: { color: '#ef4444', marginBottom: 10, textAlign: 'center' },
    navBarSafeArea: {
        backgroundColor: 'white',
        borderTopWidth: 1,
        borderTopColor: '#e5e7eb',
        paddingLeft: 0,
        paddingRight: 0,
        marginLeft: 0,
        marginRight: 0,
        zIndex: 100,
    },
    navBarRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: '100%',
        paddingVertical: 10,
    },
    navBarCenterBtn: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#4f46e5',
        alignItems: 'center',
        justifyContent: 'center',
        marginHorizontal: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 6,
    },
    navItem: { flex: 1, alignItems: 'center', justifyContent: 'center' },
    navIcon: { fontSize: 24, color: '#9ca3af' },
    navIconActive: { color: '#4f46e5' },
    navText: { fontSize: 12, color: '#6b7280' },
    navTextActive: { color: '#4f46e5', fontWeight: 'bold' },
    card: { backgroundColor: 'white', borderRadius: 12, padding: 20, marginBottom: 20, boxShadow: '0px 2px 4px rgba(0,0,0,0.1)', elevation: 3 },
    cardTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 15 },
    emptyText: { textAlign: 'center', color: '#6b7280', marginTop: 20, fontStyle: 'italic' },
    priceItem: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#f3f4f6' },
    priceItemName: { fontSize: 16, textTransform: 'capitalize' },
    priceItemValue: { fontSize: 16, fontWeight: 'bold', color: '#16a34a' },
    priceHistoryItem: { flexDirection: 'row', justifyContent: 'space-between', padding: 15, backgroundColor: 'white', borderRadius: 8, marginBottom: 10, borderWidth: 1, borderColor: '#e5e7eb' },
    inputContainer: { flexDirection: 'row', alignItems: 'center', width: '100%' },
    addButton: { backgroundColor: '#4f46e5', padding: 15, borderRadius: 10, marginLeft: 10, justifyContent: 'center', alignItems: 'center' },
    listItem: { backgroundColor: 'white', padding: 20, borderRadius: 10, marginBottom: 10, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    listItemPurchased: { backgroundColor: '#e5e7eb' },
    listItemText: { fontSize: 16, fontWeight: '500' },
    listItemTextPurchased: { textDecorationLine: 'line-through', color: '#6b7280' },
    listItemSubText: { fontSize: 12, color: '#6b7280', marginTop: 4 },
    memberItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 10 },
    memberButton: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 8 },
    memberButtonAdd: { backgroundColor: '#3b82f6' },
    memberButtonRemove: { backgroundColor: '#ef4444' },
    label: { color: '#6b7280', fontSize: 14, marginBottom: 5 },
    profileText: { fontSize: 18, marginBottom: 15, flex: 1 },
});
